name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # 1st of every month cron check

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.13"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install taxicab
        run: pip install .
        
      - name: Sanity check
        run: |
          python -c "import sys; print(sys.version)"
          pip list
          
      - name: Run tests
        run: python -m unittest tests/main.py
        
      - name: Submit to codecov
        if: ${{ matrix.python-version == '3.13' && matrix.os == 'ubuntu-latest' }}
        run: |
          pip install coverage
          coverage run -m unittest tests/*.py 
          bash <(curl -s https://codecov.io/bash)
